import { v7 as uuidv7 } from 'uuid';

/**
 * Identifiers are generated by the application, not the database.
 *
 * Two reasons, both structural rather than aesthetic:
 *
 * - An outbox row references the aggregate it describes, and both are written
 *   in the same transaction (ADR-0005). Knowing the id before the INSERT means
 *   no round trip and no RETURNING dance.
 * - An idempotent handler must be able to compute the same id from the same
 *   input on a retry (ADR-0004). That is impossible if the database assigns it.
 *
 * UUIDv7 rather than v4 because it is time-ordered: rows insert at the right
 * edge of the index instead of scattering across it, and a support engineer
 * can sort by id and get chronological order.
 */
export interface IdGenerator {
  next(): string;
}

export class Uuid7Generator implements IdGenerator {
  next(): string {
    return uuidv7();
  }
}

/**
 * A generator that counts instead of reading the clock.
 *
 * Tests that assert on stored rows need ids they can predict, for the same
 * reason they need a VirtualClock. Ids are still valid UUIDs so that database
 * column types and constraints behave identically to production.
 */
export class SequentialIdGenerator implements IdGenerator {
  #counter = 0;

  constructor(private readonly prefix = '00000000-0000-7000-8000') {}

  next(): string {
    this.#counter += 1;
    return `${this.prefix}-${this.#counter.toString(16).padStart(12, '0')}`;
  }
}
